# Generated by Django 4.2 on 2023-05-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar_url', models.URLField()),
                ('github_account_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('githubUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_repos.githubuser')),
                ('loveProgrammingLanguages', models.ManyToManyField(to='news_repos.programminglanguage')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('forks', models.IntegerField()),
                ('stargazers', models.IntegerField()),
                ('contributors', models.ManyToManyField(related_name='contributors', to='news_repos.githubuser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository', to='news_repos.githubuser')),
                ('programmingLanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos_lang', to='news_repos.programminglanguage')),
            ],
        ),
    ]
