# Generated by Django 4.2 on 2023-05-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_repos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='programmingLanguage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repos_lang', to='news_repos.programminglanguage'),
        ),
    ]
